version: "3.8"
services:
    react-app:
        container_name: react
        build: ./frontend
        ports:
            - "9000:3000"
        networks:
            - todo-app
        volumes:
            - ./frontend/src:/app/src
    api-server:
        container_name: api
        build:
            context: ./api
            target: development
        command: npm run start:dev
        ports:
            - "9001:3000"
        networks:
            - todo-app
        volumes:
            - ./api:/usr/src/app
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        networks:
            - todo-app

networks:
    todo-app:
        driver: bridge
